CREATE TABLE IF NOT EXISTS complaint_tickets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    branch_id INT UNSIGNED NOT NULL,
    customer_id INT UNSIGNED NOT NULL,
    conversation_id INT UNSIGNED NOT NULL,
    order_id INT UNSIGNED NULL,
    source_channel VARCHAR(50) NOT NULL DEFAULT 'web',
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    handling_mode VARCHAR(20) NOT NULL DEFAULT 'human',
    priority VARCHAR(20) NOT NULL DEFAULT 'medium',
    category VARCHAR(50) NOT NULL DEFAULT 'general',
    subject VARCHAR(190) NOT NULL,
    customer_message TEXT NOT NULL,
    ai_reply TEXT NULL,
    internal_note TEXT NULL,
    follow_up_reason VARCHAR(255) NULL,
    resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_complaint_branch_status (branch_id, status),
    INDEX idx_complaint_customer (customer_id),
    INDEX idx_complaint_conversation (conversation_id),
    INDEX idx_complaint_order (order_id),
    CONSTRAINT fk_complaint_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_complaint_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_complaint_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT fk_complaint_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
