CREATE TABLE IF NOT EXISTS promo_contents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    branch_id INT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    content LONGTEXT NULL,
    banner_image TEXT NULL,
    promo_code VARCHAR(100) NULL,
    discount_type VARCHAR(50) NULL,
    discount_value DECIMAL(14,2) NULL,
    start_date DATETIME NULL,
    end_date DATETIME NULL,
    publish_status VARCHAR(50) NOT NULL DEFAULT 'draft',
    published_at DATETIME NULL,
    created_by VARCHAR(255) NULL,
    updated_by VARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uq_promo_slug (slug),
    KEY idx_promo_branch (branch_id),
    KEY idx_promo_status (publish_status),
    KEY idx_promo_date (start_date, end_date)
);
